# Fast & Stable River Configuration
# Optimized for speed and meaningful erosion

# Domain - longer river
width: 200
height: 50
dx: 5.0
dy: 5.0

# Adaptive timestepping
base_dt: 0.5              # Will adapt based on CFL
total_time: 5000.0        # 5000 seconds simulation
output_interval: 200      # Output every 200 steps

# Hydraulics
discharge: 10.0           # m³/s
manning_n: 0.03
min_depth: 0.01

# Erosion parameters - tuned for visible incision
erosion_rate: 0.00005     # Erosion coefficient
critical_shear: 0.1       # Critical shear stress threshold
deposition_rate: 0.00002  # Deposition coefficient

# Initial terrain
initial_slope: 0.003      # 0.3% slope
valley_depth: 2.0
noise_amplitude: 0.1

# Inlet configuration
inlet_width: 5

# Output
output_dir: output
experiment_name: fast_river_5000s